#!/bin/bash
# Variables
NAME="pacman-export"
VERSION="1.0.0"
SYSTEM_PREFIX="/usr"
PREFIX="/usr/local"
DOCUMENT_LOCATION="$PREFIX/share/doc/$NAME"
DEFAULT_EXTENSION="paclist"
DEFAULT_FORGIN_FILE="forign.$DEFAULT_EXTENSION"
DEFAULT_REPO_FILE="repo.$DEFAULT_EXTENSION"
DEFAULT_UNIFIED_FILE="unified.$DEFAULT_EXTENSION"
DEFAULT_COMMAND="err 1 'Unknown Command'"
FUNCTION="$1"
export FILE="$2"

# Functions
err(){
  case $# in
    0)
      exit 1
      ;;
    1)
      exit $1
      ;;
    2)
      echo "$2"
      exit $1
      ;;
    3)
      echo "Error in $3 reason: $2"
      exit $1
      ;;
  esac
}
help(){
  echo "$NAME - version $VERSION"
  cat "$DOCUMENT_LOCATION/help.txt"
  err 0
}
help-all(){
  echo "$NAME - version $VERSION"
  cat "$DOCUMENT_LOCATION/help-all.txt"
  err 0
}
licence(){
  cat "$DOCUMENT_LOCATION/LICENCE"
  err 0
}
version(){
  echo $VERSION
  err 0
}
export-unified(){
  pacman -Qqe > $DEFAULT_UNIFIED_FILE
}
export-split(){
  pacman -Qqen > $DEFAULT_REPO_FILE
  pacman -Qqem > $DEFAULT_FORGIN_FILE
}
export-repo-only(){
  export-split
  rm $DEFAULT_FORGIN_FILE
}
export-forign-only(){
  export-split
  rm $DEFAULT_REPO_FILE
}
privilage-check(){
  if [ $EUID -ne 0 ];then
    if [ -e $SYSTEM_PREFIX/bin/sudo ];then
      export escilator="sudo"
    elif [ -e $SYSTEM_PREFIX/bin/doas ];then
      export escilator="doas"
    else
      err 1 "No privilage escilator"
    fi
  else
    return ""
  fi
}
pacman-install(){
  if [ -e $FILE ];then
    escilator=$(privilage-check)
    packages=$(cat $FILE)
    echo $packages | yay --repo --sudo $escilator -S -
  else
    err 1 "No file specified"
  fi
}
yay-install(){
  if [ -e $FILE ];then
    escilator=$(privilage-check)
    packages=$(cat $FILE)
    echo $packages | yay --batchinstall --topdown --sudo $escilator -S -
  else
    err 1 "No file specified"
  fi
}
yay-install-aur(){
  if [ -e $FILE ];then
    escilator=$(privilage-check)
    packages=$(cat $FILE)
    echo $packages | yay --batchinstall --sudo $escilator -Sa -
  else
    err 1 "No file specified"
  fi
}

case "$FUNCTION" in
  -h)
    help
    ;;
  --help)
    help-all
    ;;
  --licence|-l)
    licence
    ;;
  --version|-v)
    version
    ;;
  --export-unified|-e)
    export-unified
    ;;
  --export-split)
    export-split
    ;;
  --export-repo-only)
    export-repo-only
    ;;
  --export-forign-only)
    export-forign-only
    ;;
  --import|-i)
    yay-install $FILE
    ;;
  --repo)
    pacman-install $FILE
    ;;
  --aur)
    yay-install-aur "$FILE"
    ;;
  *)
    eval "$DEFAULT_COMMAND"
esac
